Add Sentry notifications
AgileVentures/agile-bot pull request #38
Opened 2016-09-30 18:37 UTC by joaopapereira

Added Post URL
/hubot/sentry-notify/:room

to receive sentry notification and to publish them in the channel :room

Added basic test Unit test of the function and a E2E test as well

2016-10-12 10:30 UTC, tansaku commented
@joaopapereira thanks for this - and sorry not to have reviewed it yet - is this ready to go from your POV?

2016-10-12 12:54 UTC, joaopapereira commented
@tansaku Yes I believe it is

2016-10-12 14:38 UTC, tansaku commented on scripts/sentry-notifications.coffee
> +    # {
do we need to keep this commented code?

2016-10-12 14:39 UTC, tansaku commented
apologies @joaopapereira could you re-open this against staging?

I need up update the contributing doc

2016-10-12 14:40 UTC, tansaku commented
green locally for me

2016-10-12 15:08 UTC, joaopapereira commented on scripts/sentry-notifications.coffee
> +    # {
This is not commented code, but the post message that we receive from sentry

2016-10-12 15:09 UTC, joaopapereira commented
Just changed the base to staging

2016-10-12 15:10 UTC, joaopapereira commented on scripts/sentry-notifications.coffee
> +    # {
If you want I can add a comment saying what this is or can just remove it all

2016-10-13 14:19 UTC, tansaku commented on scripts/sentry-notifications.coffee
> +    # {
ah, you're saying it's an example of what we receive?  ah good to have then - yeah, add a note to that effect i guess

2016-10-13 14:19 UTC, tansaku commented on scripts/sentry-notifications.coffee
> +#   Posts Hangouts Notifications from AgileVentures to Slack and Gitter.
should this change?

2016-10-13 14:19 UTC, tansaku commented on scripts/sentry-notifications.coffee
> +#   sampritipanda
should this change?

2016-10-13 14:20 UTC, tansaku commented
thanks @joaopapereira 

@mtc2013 any thoughts on this one?

2016-10-17 13:47 UTC, mtc2013 requested changes
Please confirm if this works for you.

2016-10-17 13:47 UTC, mtc2013 commented on spec/sentryIntegrationSpec.coffee
> +makeRequest = (body, done) ->
@tansaku @joaopapereira it appears we don't need this function in this particular file. i confirmed by commenting it out and the specs still pass.

2016-10-17 17:13 UTC, mtc2013 commented on spec/sentryIntegrationSpec.coffee
> +makeRequest = (body, done) ->
@tansaku @joaopapereira  i'd advise deleting this makeRequest function from this spec.

2016-10-24 12:07 UTC, mtc2013 commented
Closing this.  Added a new pr integrating the suggested changes here https://github.com/AgileVentures/agile-bot/pull/40

2016-10-24 12:08 UTC, closed without merging